### PR TITLE
Reduce log spam in carbonserver

### PR DESCRIPTION
**Pull request by yashlyft**
/cc @theatrus

### CODE REVIEW

**Comment by grobian** [comment]
do you need this still, or not?

**Comment by dgryski** [comment]
It probably should go into our tree too. It also points out that I missed a few calls moving to our customer logger.

**Comment by grobian** [comment]
@dgryski: will you fix it?

**Comment by dgryski** [comment]
Yes, I'll clean up the logging when I have some time (probably tomorrow)

**Pull request closed without merging**
